name: Build and Push to ACR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_TOKEN }}" | docker login eqacr535e7d69.azurecr.io --username eqacr535e7d69 --password-stdin

    - name: Build and push Docker image
      run: |
        docker build . -t eqacr535e7d69.azurecr.io/myapp:latest
        docker push eqacr535e7d69.azurecr.io/myapp:latest